[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "ch-tools"
version = "2.526.48925339"
license = "MIT"
description = "ch-tools is a set of tools for administration and diagnostics of ClickHouse DBMS."

authors = [
    "Alexander Burmak <alex-burmak@yandex-team.ru>",
    "Dmitry Starov <dstaroff@yandex-team.ru>",
    # {name = "Anton Ivashkin", email="iantonspb@yandex-team.ru"},
    # {name = "Grigory Pervakov", email="pervakovg@yandex-team.ru"},
    # {name = "Petr Nuzhnov", email="petrnuzhnov@yandex-team.ru"},
    # {name = "Egor Medvedev", email="egor-medvedev@yandex-team.ru"},
    # {name = "Aleksei Filatov", email="alexfvk@yandex-team.ru"},
    # {name = "Evgeny Dyukov", email="secwall@yandex-team.ru"},
    # {name = "Evgeny Strizhnev", email="estrizhnev@yandex-team.ru"},
    # {name = "Vadim Volodin", email="vadim-volodin@yandex-team.ru"},
    # {name = "Anton Chaporgin", email="chapson@yandex-team.ru"},
    # {name = "Evgenii Kopanev", email="ekopanev@yandex-team.ru"},
    # {name = "Mikhail Kot", email="myrrc@yandex-team.ru"},
]

maintainers = [
    "Alexander Burmak <alex-burmak@yandex-team.ru>",
    # {name = "Dmitry Starov", email="dstaroff@yandex-team.ru"},
    # {name = "Anton Ivashkin", email="iantonspb@yandex-team.ru"},
    # {name = "Grigory Pervakov", email="pervakovg@yandex-team.ru"},
    # {name = "Petr Nuzhnov", email="petrnuzhnov@yandex-team.ru"},
    # {name = "Egor Medvedev", email="egor-medvedev@yandex-team.ru"},
    # {name = "Aleksei Filatov", email="alexfvk@yandex-team.ru"},
    # {name = "Evgenii Kopanev", email="ekopanev@yandex-team.ru"},
    # {name = "Mikhail Kot", email="myrrc@yandex-team.ru"},
]

readme = "README.md"

repository = "https://github.com/yandex/ch-tools"
homepage = "https://github.com/yandex/ch-tools"

keywords=[
    "clickhouse",
    "database",
    "monitoring",
    "diagnostics",
    "administration",
]

classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "Intended Audience :: System Administrators",
    "License :: OSI Approved :: MIT License",
    "Operating System :: MacOS",
    "Operating System :: POSIX :: BSD",
    "Operating System :: POSIX :: Linux",
    "Operating System :: Unix",
    "Environment :: Console",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Topic :: Database",
    "Typing :: Typed",
]

# packages

# [tool.flit.sdist]
# include = ["resources/"]
include = ["resources/"]

# requires-python = ">=3.6.2"

[tool.poetry.dependencies]
python = "^3.6.2"
boto3 = "*"
click = "*"
cloup = "*"
deepdiff = "*"
dnspython = "*"
file_read_backwards = "*"
humanfriendly = "*"
jinja2 = "*"
kazoo = "*"
lxml = "*"
psutil = "*"
pygments = "*"
pyopenssl = "*"
python-dateutil = "*"
pyyaml = "*"
requests = "*"
tabulate = "*"
tenacity = "*"
termcolor = "*"
tqdm = "*"
xmltodict = "*"
typing-extensions = "*"

[tool.poetry.dev-dependencies]
flit = "*"
black = "*"
isort = {version = "^5.0.0", extras = ["pyproject"]}
mypy = "*"
types-pyyaml = "*"
types-requests = "*"
types-python-dateutil = "*"
types-tabulate = "*"
types-pyOpenSSL = "*"
types-setuptools = "*"
#pylint = "^2.13"
#bandit = "*"
behave = "*"
docker = "*"
docker-compose = "*"
pyhamcrest = "*"
pytest = "*"

[tool.poetry.scripts]
chadmin = "ch_tools.chadmin.chadmin_cli:main"
ch-monitoring = "ch_tools.monrun_checks.main:main"
keeper-monitoring = "ch_tools.monrun_checks_keeper.main:main"
ch-s3-credentials = "ch_tools.s3_credentials.main:main"

[tool.isort]
profile = "black"
